"""Milestone 3 trust spine: a separate, post-plan, locally injectable kernel.

This package is *not* a cloud runtime and does not extend the planning graph.
It is a small, bounded state machine that takes an immutable
:class:`~agent_runtime.trust_spine.types.FrozenPlan` and drives a fixed trace:

``prisma_validate`` (with up to three pre-approval ``prisma_repair``
attempts) -> ``deterministic_policy`` -> ``vale_verify`` -> a server-side
simulation approval -> a distinct server-side production approval, which
atomically seals the run -> ``flow_dispatch`` -> ``ledger_reconcile`` ->
``forge_certify``.

Everything external is injected as a narrow port (see
:mod:`~agent_runtime.trust_spine.protocols`); the package ships no ambient
implementation, no client, no adapter and no I/O of its own.
"""

from __future__ import annotations

from .kernels import (
    FlowKernel,
    ForgeKernel,
    LedgerKernel,
    PolicyKernel,
    PrismaKernel,
    SealedExecution,
    ValeKernel,
    assert_no_model_surface,
    build_execution_bundle,
    chain_values,
    expected_effect_digest,
    has_executable_key_name,
    has_model_surface_name,
    node_input_digest,
    replay_chain,
    simulation_subject_digest,
    validate_payload,
    verify_approval,
)
from .protocols import (
    ApprovalAuthority,
    CertificationPort,
    ModelCapable,
    ModelRepairAdapter,
    ReconciliationReader,
    StateStore,
    TemplateDispatcher,
)
from .runtime import Journal, TrustSpineRuntime
from .types import (
    DEFAULT_BUDGET,
    EMPTY_MAP,
    MAX_MODEL_CALLS,
    MAX_REPAIRS,
    MODEL_NODES,
    NODE_PLAN,
    PHASE_ORDER,
    POST_PRODUCTION_MODEL_CALLS,
    SEALING_PHASE,
    SIDE_EFFECT_NODES,
    ApprovalError,
    ApprovalQuery,
    ApprovalRecord,
    BudgetError,
    BudgetPolicy,
    CanonicalError,
    CanonicalMap,
    Certificate,
    CertificationError,
    CertificationRequest,
    ConcurrencyError,
    Decision,
    DispatchError,
    DispatchReceipt,
    DispatchRequest,
    DurabilityError,
    ExecutionBundle,
    FailureCode,
    FrozenPlan,
    NodeName,
    NodeRecord,
    NodeStatus,
    ParameterBinding,
    ParameterSpec,
    PolicyConfig,
    PolicyDecision,
    PolicyError,
    ReconciliationError,
    ReconciliationQuery,
    ReconciliationReport,
    RecordError,
    RegistryError,
    RegistryTemplate,
    RepairRequest,
    RunCheckpoint,
    RunPhase,
    RunRequest,
    RunResult,
    SealedBundle,
    Stage,
    TrustSpineError,
    TypedValue,
    ValeVerdict,
    ValidatedProposal,
    ValidationError,
    ValueKind,
    canonical_json,
    chain_step,
    derive_approval_key,
    derive_effect_key,
    derive_idempotency_key,
    digest_of,
    digest_of_text,
    error_digest,
    freeze,
    genesis_digest,
    is_sealed_phase,
    phase_index,
)

__all__ = [
    "ApprovalAuthority",
    "ApprovalError",
    "ApprovalQuery",
    "ApprovalRecord",
    "BudgetError",
    "BudgetPolicy",
    "CanonicalError",
    "CanonicalMap",
    "Certificate",
    "CertificationError",
    "CertificationPort",
    "CertificationRequest",
    "ConcurrencyError",
    "DEFAULT_BUDGET",
    "Decision",
    "DispatchError",
    "DispatchReceipt",
    "DispatchRequest",
    "DurabilityError",
    "EMPTY_MAP",
    "ExecutionBundle",
    "FailureCode",
    "FlowKernel",
    "ForgeKernel",
    "FrozenPlan",
    "Journal",
    "LedgerKernel",
    "MAX_MODEL_CALLS",
    "MAX_REPAIRS",
    "MODEL_NODES",
    "ModelCapable",
    "ModelRepairAdapter",
    "NODE_PLAN",
    "NodeName",
    "NodeRecord",
    "NodeStatus",
    "PHASE_ORDER",
    "POST_PRODUCTION_MODEL_CALLS",
    "ParameterBinding",
    "ParameterSpec",
    "PolicyConfig",
    "PolicyDecision",
    "PolicyError",
    "PolicyKernel",
    "PrismaKernel",
    "ReconciliationError",
    "ReconciliationQuery",
    "ReconciliationReader",
    "ReconciliationReport",
    "RecordError",
    "RegistryError",
    "RegistryTemplate",
    "RepairRequest",
    "RunCheckpoint",
    "RunPhase",
    "RunRequest",
    "RunResult",
    "SEALING_PHASE",
    "SIDE_EFFECT_NODES",
    "SealedBundle",
    "SealedExecution",
    "Stage",
    "StateStore",
    "TemplateDispatcher",
    "TrustSpineError",
    "TrustSpineRuntime",
    "TypedValue",
    "ValeKernel",
    "ValeVerdict",
    "ValidatedProposal",
    "ValidationError",
    "ValueKind",
    "assert_no_model_surface",
    "build_execution_bundle",
    "canonical_json",
    "chain_step",
    "chain_values",
    "derive_approval_key",
    "derive_effect_key",
    "derive_idempotency_key",
    "digest_of",
    "digest_of_text",
    "error_digest",
    "expected_effect_digest",
    "freeze",
    "genesis_digest",
    "has_executable_key_name",
    "has_model_surface_name",
    "is_sealed_phase",
    "node_input_digest",
    "phase_index",
    "replay_chain",
    "simulation_subject_digest",
    "validate_payload",
    "verify_approval",
]
