#!/usr/bin/env python3
"""Generate the synthetic JDE cartridge seed.

Writes data/jde_e1_ibmi/init.sql with a volume that behaves like a real
migration slice rather than a unit test:

  f0101   address book, stored as raw 65-byte IBM i records in a bytea column
          (COMP-3 packed decimal + EBCDIC cp037), which is what the source
          query returns and what the Beam DoFn converts
  f0911   account ledger with CYYDDD julian dates
  f9860 / f98711   the metadata catalogs the fleet reads to learn the layout
  f0911_delta      change stream for the incremental watermark

Defect rate is 1.2% for the ledger and 0.8% for the address book. Published
legacy-ERP migration assessments put structural defect rates in the 0.5-3%
band; the low end of that is both realistic and dense enough that a LIMIT 10
query still lands on several.

Everything here is synthetic. No vendor data, schema export, or driver is used.
"""
from __future__ import annotations

import binascii
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data/jde_e1_ibmi/init.sql"

SEED = 20260901          # fixed so the image is reproducible
LEDGER_ROWS = 5_000
ADDRESS_ROWS = 2_500
DELTA_ROWS = 400
LEDGER_DEFECT_RATE = 0.012
ADDRESS_DEFECT_RATE = 0.008

RECORD_SIZE, ABAN8_SIZE, ABALPH_SIZE = 65, 5, 40

FIRST = ("Northstar", "Blue Heron", "Juniper", "Copper Finch", "Granite", "Harbor",
         "Cedar Ridge", "Ironwood", "Silver Lake", "Redwood", "Sandpiper", "Kestrel",
         "Meridian", "Alderman", "Beacon Hill", "Cobalt", "Dunmore", "Everline")
SECOND = ("Components", "Manufacturing", "Industrial", "Systems", "Logistics",
          "Fabrication", "Materials", "Instruments", "Castings", "Assemblies")
SUFFIX = ("LLC", "Ltd", "GmbH", "KK", "Inc", "SA", "Pty", "BV")
COUNTRY = ("US", "CA", "DE", "JP", "GB", "FR", "AU", "NL", "SE", "MX")
DOC_TYPES = ("JE", "PV", "RI", "AE", "PR")
LEDGERS = ("AA", "BA", "CA")


def to_comp3(number: int, width: int, *, bad_sign: bool = False) -> bytes:
    """Pack an integer as COBOL COMP-3. bad_sign emits an invalid nibble."""
    digits = str(abs(number))
    digits += "F" if bad_sign else ("C" if number >= 0 else "D")
    return binascii.unhexlify(digits.rjust(width * 2, "0")) if not bad_sign else \
        binascii.unhexlify(digits.rjust(width * 2, "0")).replace(b"\x0f", b"\x0a")[:width] or b"\x00" * width


def address_record(number: int, name: str, country: str, *, defect: str | None) -> bytes:
    """One F0101 row exactly as IBM i would hold it.

    Both defects are structural faults in the COMP-3 field, because cp037 maps
    all 256 byte values -- there is no such thing as undecodable EBCDIC text,
    so a text-side "defect" would decode cleanly and the fixture would be
    lying about which rows are bad.
    """
    if defect == "comp3_sign":
        # Sign nibble outside {C, D, F}.
        aban8 = binascii.unhexlify(str(number).rjust(ABAN8_SIZE * 2 - 1, "0") + "A")
    elif defect == "comp3_digit":
        # A non-decimal nibble in a digit position.
        digits = str(number).rjust(ABAN8_SIZE * 2 - 1, "0")
        aban8 = binascii.unhexlify("B" + digits[1:] + "C")
    else:
        aban8 = to_comp3(number, ABAN8_SIZE)
    alpha = name[:ABALPH_SIZE].ljust(ABALPH_SIZE).encode("cp037")
    tax = country.ljust(20).encode("cp037")
    return aban8 + alpha[:ABALPH_SIZE] + tax


def julian(year: int, ordinal: int) -> int:
    """CYYDDD: century flag, two-digit year, day of year."""
    return (1 if year >= 2000 else 0) * 100_000 + (year % 100) * 1_000 + ordinal


def leap(year: int) -> bool:
    return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)


def main() -> int:
    rng = random.Random(SEED)
    lines: list[str] = []
    add = lines.append

    add("-- Project-owned synthetic JDE/IBM i-shaped data. This is not JDE or Db2 for i.")
    add(f"-- Generated by scripts/generate_jde_seed.py (seed {SEED}). Do not hand-edit.")
    add("")
    add("""CREATE TABLE f9860 (
  object_name text PRIMARY KEY,
  object_type text NOT NULL,
  object_library text NOT NULL
);
CREATE TABLE f98711 (
  table_name text NOT NULL,
  field_name text NOT NULL,
  data_type text NOT NULL,
  ordinal integer NOT NULL,
  PRIMARY KEY (table_name, field_name)
);
CREATE TABLE f0101 (
  aban8 integer PRIMARY KEY,
  abalph text NOT NULL,
  abtax text NOT NULL,
  record_bytes bytea NOT NULL,
  record_length integer NOT NULL,
  fixture_class text NOT NULL CHECK (fixture_class IN ('snapshot', 'invalid')),
  defect text
);
COMMENT ON TABLE f0101 IS
  'Address book as the source system presents it. ABAN8/ABALPH/ABTAX are what a
   JDBC client sees, because the driver decodes COMP-3 and EBCDIC on read.
   record_bytes is the same row as it sits in the physical file, which is what a
   bulk export or file-level read actually yields.';
COMMENT ON COLUMN f0101.record_bytes IS
  'ABAN8 bytes 0-4 COMP-3, ABALPH bytes 5-44 cp037, ABTAX bytes 45-64 cp037.';
CREATE TABLE f0911 (
  company text NOT NULL,
  document_type text NOT NULL,
  document_number bigint NOT NULL,
  line_number integer NOT NULL,
  ledger_type text NOT NULL,
  upmj integer NOT NULL,
  upmt integer NOT NULL,
  amount_minor bigint NOT NULL,
  fixture_class text NOT NULL CHECK (fixture_class IN ('snapshot', 'invalid')),
  defect text,
  PRIMARY KEY (company, document_type, document_number, line_number, ledger_type)
);
CREATE TABLE f0911_delta (
  sequence integer PRIMARY KEY,
  operation text NOT NULL CHECK (operation IN ('insert', 'update', 'delete')),
  company text NOT NULL,
  document_type text NOT NULL,
  document_number bigint NOT NULL,
  line_number integer NOT NULL,
  ledger_type text NOT NULL,
  upmj integer NOT NULL,
  upmt integer NOT NULL
);""")
    add("")

    add("INSERT INTO f9860 VALUES")
    add(",\n".join([
        "  ('F0101', 'TBLE', 'PRODDTA')",
        "  ('F0911', 'TBLE', 'PRODDTA')".lstrip(),
        "  ('F0911_DELTA', 'TBLE', 'PRODDTA')".lstrip(),
    ]).replace("\n  (", ",\n  (") + ";")
    add("")

    catalog = [
        ("F0101", "ABAN8", "COMP-3", 1), ("F0101", "ABALPH", "EBCDIC_CP037", 2),
        ("F0101", "ABTAX", "EBCDIC_CP037", 3),
        ("F0911", "UPMJ", "CYYDDD", 1), ("F0911", "UPMT", "HHMMSS", 2),
        ("F0911", "AA", "INTEGER_MINOR_UNITS", 3), ("F0911", "DOC", "NUMERIC", 4),
        ("F0911", "DCT", "CHAR", 5), ("F0911", "KCO", "CHAR", 6),
    ]
    add("INSERT INTO f98711 VALUES")
    add(",\n".join(f"  ('{t}', '{f}', '{d}', {o})" for t, f, d, o in catalog) + ";")
    add("")

    # ---- f0101: raw IBM i records -------------------------------------
    defects = {"comp3_sign", "comp3_digit"}
    address_values: list[str] = []
    bad_addresses = 0
    for number in range(1, ADDRESS_ROWS + 1):
        name = f"{rng.choice(FIRST)} {rng.choice(SECOND)} {rng.choice(SUFFIX)}"
        country = rng.choice(COUNTRY)
        defect = rng.choice(sorted(defects)) if rng.random() < ADDRESS_DEFECT_RATE else None
        record = address_record(number, name, country, defect=defect)
        if len(record) != RECORD_SIZE:
            record = record[:RECORD_SIZE].ljust(RECORD_SIZE, b"\x40")
        bad_addresses += 1 if defect else 0
        # A JDBC client sees decoded columns; a file-level read sees the bytes.
        # Rows with a structural fault cannot be presented by the driver either,
        # so their readable columns carry the source system's own null marker.
        readable_name = "?" if defect else name.replace("'", "''")
        readable_tax = "?" if defect else country
        address_values.append(
            f"  ({number}, '{readable_name}', '{readable_tax}', "
            f"'\\x{record.hex()}'::bytea, {RECORD_SIZE}, "
            f"'{'invalid' if defect else 'snapshot'}', "
            f"{'NULL' if defect is None else chr(39) + defect + chr(39)})")
    add("INSERT INTO f0101 VALUES")
    add(",\n".join(address_values) + ";")
    add("")

    # ---- f0911: ledger with CYYDDD dates ------------------------------
    ledger_values: list[str] = []
    seen: set[tuple] = set()
    bad_ledger = 0
    document = 700_100
    while len(ledger_values) < LEDGER_ROWS:
        document += 1
        company = f"{rng.randint(1, 4):05d}"
        doc_type = rng.choice(DOC_TYPES)
        ledger = rng.choice(LEDGERS)
        line = rng.randint(1, 4)
        key = (company, doc_type, document, line, ledger)
        if key in seen:
            continue
        seen.add(key)

        year = rng.randint(2019, 2026)
        if rng.random() < LEDGER_DEFECT_RATE:
            bad_ledger += 1
            if rng.random() < 0.5:
                defect, upmj = "non_leap_year_ordinal_366", julian(year if not leap(year) else year + 1, 366)
            else:
                defect, upmj = "zero_ordinal", julian(year, 0)
        else:
            defect = None
            upmj = julian(year, rng.randint(1, 366 if leap(year) else 365))
        upmt = rng.randint(0, 23) * 10_000 + rng.randint(0, 59) * 100 + rng.randint(0, 59)
        amount = rng.randint(-500_000, 5_000_000)
        ledger_values.append(
            f"  ('{company}','{doc_type}',{document},{line},'{ledger}',{upmj},{upmt},{amount},"
            f"'{'invalid' if defect else 'snapshot'}',"
            f"{'NULL' if defect is None else chr(39) + defect + chr(39)})")
    add("INSERT INTO f0911 VALUES")
    add(",\n".join(ledger_values) + ";")
    add("")

    # ---- f0911_delta: the incremental watermark -----------------------
    delta_values = []
    for sequence in range(1, DELTA_ROWS + 1):
        operation = rng.choice(("insert", "update", "delete"))
        year = rng.randint(2025, 2026)
        delta_values.append(
            f"  ({sequence},'{operation}','{rng.randint(1, 4):05d}','{rng.choice(DOC_TYPES)}',"
            f"{rng.randint(700_101, document)},{rng.randint(1, 4)},'{rng.choice(LEDGERS)}',"
            f"{julian(year, rng.randint(1, 365))},{rng.randint(0, 235959)})")
    add("INSERT INTO f0911_delta VALUES")
    add(",\n".join(delta_values) + ";")
    add("")

    add("""CREATE INDEX f0911_upmj_idx ON f0911 (upmj);
CREATE INDEX f0911_fixture_idx ON f0911 (fixture_class);
CREATE INDEX f0101_fixture_idx ON f0101 (fixture_class);
CREATE ROLE cartridge_reader LOGIN PASSWORD 'synthetic-only-reader';
GRANT CONNECT ON DATABASE keraun_jde TO cartridge_reader;
GRANT USAGE ON SCHEMA public TO cartridge_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO cartridge_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO cartridge_reader;""")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  f0101        {ADDRESS_ROWS:>6} rows  {bad_addresses:>4} invalid "
          f"({bad_addresses / ADDRESS_ROWS:.2%})")
    print(f"  f0911        {LEDGER_ROWS:>6} rows  {bad_ledger:>4} invalid "
          f"({bad_ledger / LEDGER_ROWS:.2%})")
    print(f"  f0911_delta  {DELTA_ROWS:>6} rows")
    print(f"  f98711       {len(catalog):>6} rows")
    print(f"  size         {OUT.stat().st_size / 1_048_576:.2f} MiB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
